spring:
  docker:
    compose:
      enabled: false
kokoro:
  cors:
    allow-origin:
      - http://localhost:5173
      - https://kokoro.health
      - https://api.kokoro.health
      - ${FRONTEND_URL}
springdoc:
  api-docs:
    enabled: false
management:
  endpoint:
    health:
      show-details: never
      show-components: never
