spring:
  docker:
    compose:
      enabled: false
kokoro:
  cors:
    allow-origin:
      - http://localhost:5173
      - https://kokoro.health
      - https://api.kokoro.health
      - ${FRONTEND_URL}
#springdoc:
#  api-docs:
#    enabled: false
server:
  forward-headers-strategy: framework
  port: 8080
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs/swagger
