spring:
  docker:
    compose:
      enabled: false
kokoro:
  cors:
    allow-origin:
      - localhost:5173
      - kokoro.health
      - api.kokoro.health
      - ${FRONTEND_URL}
#springdoc:
#  api-docs:
#    enabled: false
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs/swagger
